/**
 * content-collections — Slice 0: the content-DB module.
 *
 * The ONE narrow place in the app where runtime SQL runs against the per-Site
 * D1, for `content_*` collection tables ONLY. The Drizzle `Db` port
 * (`lib/ports/db.ts`) stays Drizzle-only for built-in tables — this module is
 * the controlled widening to `d1.prepare()/exec()`, deliberately kept NARROW
 * and behind the Slice-0 fence (`./fence.ts`): every statement is validated
 * before it touches D1, so no caller can run unfenced raw SQL.
 *
 * Read path = parameterized SELECT only. Write/DDL path = a SINGLE
 * system-generated DDL/DML statement. Both go through `assertStatement` first.
 */
import { getCloudflareContext } from "@opennextjs/cloudflare";
import { assertStatement } from "./fence.ts";

/** Max rows any single read may return — a hard backstop on the read path. */
export const MAX_READ_ROWS = 1000;

/**
 * Minimal D1 surface we use. Decoupled from the full `D1Database` type so this
 * module is testable against an in-memory fake (see `content-db.test.mjs`).
 */
export interface D1Like {
  prepare(sql: string): {
    bind(...params: unknown[]): {
      all(): Promise<{ results: unknown[] }>;
      run(): Promise<{ meta?: { changes?: number } }>;
    };
    all(): Promise<{ results: unknown[] }>;
    run(): Promise<{ meta?: { changes?: number } }>;
  };
  exec(sql: string): Promise<unknown>;
}

/** Resolve the live per-Site D1 binding. The ONLY env.DB read in this module. */
async function liveDb(): Promise<D1Like> {
  const { env } = await getCloudflareContext({ async: true });
  return env.DB as unknown as D1Like;
}

/**
 * Run a fenced, parameterized SELECT over content_* tables. Validates the SQL
 * (read mode) BEFORE binding/executing. Caller passes only the system-generated
 * SQL + bound params — never interpolated user input.
 */
export async function contentSelect<T = Record<string, unknown>>(
  sql: string,
  params: unknown[] = [],
  db?: D1Like,
): Promise<T[]> {
  assertStatement(sql, "read");
  const d1 = db ?? (await liveDb());
  const stmt = d1.prepare(sql);
  const { results } = await (params.length ? stmt.bind(...params).all() : stmt.all());
  // Backstop: never hand back more than the cap even if a generated LIMIT slips.
  return (results as T[]).slice(0, MAX_READ_ROWS);
}

/**
 * Run a fenced, parameterized write (INSERT/UPDATE/DELETE) over content_* tables.
 * Validates (write mode) first. Returns affected row count.
 */
export async function contentWrite(
  sql: string,
  params: unknown[] = [],
  db?: D1Like,
): Promise<number> {
  assertStatement(sql, "write");
  const d1 = db ?? (await liveDb());
  const stmt = d1.prepare(sql);
  const res = await (params.length ? stmt.bind(...params).run() : stmt.run());
  return res.meta?.changes ?? 0;
}

/**
 * Run a fenced, SYSTEM-generated DDL statement (CREATE / ALTER / DROP) for a
 * content_* table. Validates (write mode) first. DDL takes no bound params (D1
 * `exec` doesn't bind); the statement is wholly generated by us from a typed
 * field-schema (Slice 1), never assembled from raw user strings.
 */
export async function contentDdl(sql: string, db?: D1Like): Promise<void> {
  assertStatement(sql, "write");
  const d1 = db ?? (await liveDb());
  // D1's `exec()` SPLITS its input on newlines and runs each line as a separate
  // statement — so a multi-line `CREATE TABLE content_x (\n  col,\n  ...\n)`
  // gets chopped (line 1 `CREATE TABLE content_x (` runs alone → "incomplete
  // input"). Our system-generated DDL is always exactly ONE statement (the fence
  // rejects multi-statement), so run it via the prepared-statement path, which
  // executes the single statement intact regardless of newlines.
  await d1.prepare(sql).run();
}
