/**
 * Custom worker entrypoint (path-locales-edge-cache) — the wrangler `main`.
 *
 * Wraps the generated OpenNext handler (documented OpenNext pattern) to stamp
 * `Cache-Control` + `Cache-Tag` on opted-in published pages: RSC pages cannot
 * set response headers and Next marks dynamic pages `no-store`, so the ONLY
 * place edge-cache headers can be set is here, after the handler returns.
 * It also rewrites `<html lang>` on published-page HTML to the URL's content
 * locale (the root layout can only stamp the visitor's admin-UI locale).
 *
 * Flow per response: the pure gate (`isEdgeCacheCandidate`) rejects non-GET /
 * non-200 / Set-Cookie / system-path traffic for free; survivors get ONE extra
 * D1 lookup (locale peel + the same `resolvePage` walk the route uses) to read
 * the page's `cache_max_age` opt-in. Since Workers Cache serves hits without
 * invoking the worker at all, that lookup only ever runs on cache misses.
 * Everything is best-effort: any error falls through to the untouched response.
 *
 * Verifying: headers are unit-tested (edge-cache.test.ts); real hit/miss
 * behavior (`cf-cache-status`) is only observable on a DEPLOYED site — neither
 * `next dev` nor local wrangler preview enforces the real edge cache.
 */
// @ts-ignore — `.open-next/worker.js` is generated by the OpenNext build:
// resolvable after a build, absent on a clean checkout (so not expect-error).
import { default as handler } from "./.open-next/worker.js";
import { cfDb } from "./src/lib/ports/db";
import { getContentLocales } from "./src/db/settings-store";
import { peelLocaleSegment, resolveSlugPath } from "./src/lib/render/slug";
import { resolvePage } from "./src/lib/render/resolve-page";
import {
  isEdgeCacheCandidate,
  pathnameSegments,
  edgeCacheHeaders,
  isHtmlContentType,
  markdownVariantRewrite,
  llmsTxtCacheHeaders,
  sitemapXmlCacheHeaders,
} from "./src/lib/render/edge-cache";

export default {
  async fetch(request, env, ctx) {
    // Markdown page variants (seo-robots): a public `/<path>.md` GET is served by
    // the internal `/api/md/<path>` route (which builds the plan + serializes —
    // that stack can't live here in the lean worker). Rewrite the URL BEFORE
    // OpenNext so the internal route runs; the response's `.md` URL is what the
    // caller sees. Cheap string gate, no D1 on the hot path. `/api/*` is
    // edge-cache-excluded, so the rewritten request never gets a page Cache-Tag.
    const mdUrl =
      request.method === "GET" ? markdownVariantRewrite(request.url) : null;
    if (mdUrl) {
      return handler.fetch(new Request(mdUrl, request), env, ctx);
    }
    const response: Response = await handler.fetch(request, env, ctx);
    try {
      // /llms.txt explicit carve-out (seo-robots): the dot gate excludes it
      // (isEdgeCacheCandidate rejects dotted root paths), so opt it back in with
      // its OWN tag here — a FIXED /llms.txt match, never a loosening of the dot
      // gate. Purge coverage (page write/publish/delete/rename, brand save, llms
      // template save) clears LLMS_CACHE_TAG. GET 200 only; no per-request D1.
      if (request.method === "GET" && response.status === 200) {
        const pathname = new URL(request.url).pathname;
        // Each dotted-root cacheable file gets its OWN carve-out fn + tag (never
        // widen the dot gate — CAVEATS). /sitemap.xml is crawler-hammered and
        // does a per-request D1 read today; this edge-caches it under `sitemap`,
        // purged by every page-write site (publish/unpublish/delete/rename).
        const dotFile =
          llmsTxtCacheHeaders(pathname) ?? sitemapXmlCacheHeaders(pathname);
        if (dotFile) {
          const out = new Response(response.body, response);
          out.headers.set("Cache-Control", dotFile.cacheControl);
          out.headers.set("Cache-Tag", dotFile.cacheTag);
          return out;
        }
      }
      if (
        !isEdgeCacheCandidate({
          method: request.method,
          pathname: new URL(request.url).pathname,
          status: response.status,
          hasSetCookie: response.headers.has("Set-Cookie"),
        })
      ) {
        return response;
      }
      const db = cfDb(env.DB);
      const contentLocales = await getContentLocales(db);
      const { locale, rest } = peelLocaleSegment(
        pathnameSegments(new URL(request.url).pathname),
        contentLocales.locales,
        contentLocales.default,
      );
      // Stage 2: locale-aware walk — localized-slug URLs stamp the same tags.
      const resolved = await resolvePage(db, resolveSlugPath(rest), locale);
      if (!resolved) return response;
      let out = response;
      const headers = edgeCacheHeaders(resolved.page.cacheMaxAge, resolved.page.id);
      if (headers) {
        out = new Response(out.body, out);
        out.headers.set("Cache-Control", headers.cacheControl);
        out.headers.set("Cache-Tag", headers.cacheTag);
      }
      // The root layout stamps `<html lang>` with the visitor's ADMIN-UI locale
      // (NEXT_LOCALE cookie / Accept-Language) — an RSC layout can't see the
      // pathname. On published pages the URL's content locale is the truth, and
      // the layout value would both mislabel content for SEO and bake the FIRST
      // visitor's browser language into the cached HTML. Rewrite it here, before
      // Workers Cache stores the response (HTMLRewriter streams; headers carry over).
      if (isHtmlContentType(out.headers.get("Content-Type"))) {
        out = new HTMLRewriter()
          .on("html", { element: (el) => void el.setAttribute("lang", locale) })
          .transform(out);
      }
      return out;
    } catch {
      // Best-effort (CAVEATS): a cache-stamping failure must never break serving.
      return response;
    }
  },
} satisfies ExportedHandler<CloudflareEnv>;

// The OpenNext build currently emits these Durable Object exports even with the
// "dummy" cache config; wrangler resolves them from the generated bundle.
// @ts-ignore — same generated-module caveat as the import above.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
