/**
 * Custom worker entrypoint (path-locales-edge-cache) — the wrangler `main`.
 *
 * Wraps the generated OpenNext handler (documented OpenNext pattern) to stamp
 * `Cache-Control` + `Cache-Tag` on opted-in published pages: RSC pages cannot
 * set response headers and Next marks dynamic pages `no-store`, so the ONLY
 * place edge-cache headers can be set is here, after the handler returns.
 *
 * Flow per response: the pure gate (`isEdgeCacheCandidate`) rejects non-GET /
 * non-200 / Set-Cookie / system-path traffic for free; survivors get ONE extra
 * D1 lookup (locale peel + the same `resolvePage` walk the route uses) to read
 * the page's `cache_max_age` opt-in. Since Workers Cache serves hits without
 * invoking the worker at all, that lookup only ever runs on cache misses.
 * Everything is best-effort: any error falls through to the untouched response.
 *
 * Verifying: headers are unit-tested (edge-cache.test.ts); real hit/miss
 * behavior (`cf-cache-status`) is only observable on a DEPLOYED site — neither
 * `next dev` nor local wrangler preview enforces the real edge cache.
 */
// @ts-ignore — `.open-next/worker.js` is generated by the OpenNext build:
// resolvable after a build, absent on a clean checkout (so not expect-error).
import { default as handler } from "./.open-next/worker.js";
import { cfDb } from "./src/lib/ports/db";
import { getContentLocales } from "./src/db/settings-store";
import { peelLocaleSegment, resolveSlugPath } from "./src/lib/render/slug";
import { resolvePage } from "./src/lib/render/resolve-page";
import {
  isEdgeCacheCandidate,
  pathnameSegments,
  edgeCacheHeaders,
} from "./src/lib/render/edge-cache";

export default {
  async fetch(request, env, ctx) {
    const response: Response = await handler.fetch(request, env, ctx);
    try {
      if (
        !isEdgeCacheCandidate({
          method: request.method,
          pathname: new URL(request.url).pathname,
          status: response.status,
          hasSetCookie: response.headers.has("Set-Cookie"),
        })
      ) {
        return response;
      }
      const db = cfDb(env.DB);
      const contentLocales = await getContentLocales(db);
      const { rest } = peelLocaleSegment(
        pathnameSegments(new URL(request.url).pathname),
        contentLocales.locales,
        contentLocales.default,
      );
      const resolved = await resolvePage(db, resolveSlugPath(rest));
      const headers = resolved
        ? edgeCacheHeaders(resolved.page.cacheMaxAge, resolved.page.id)
        : null;
      if (!headers) return response;
      const stamped = new Response(response.body, response);
      stamped.headers.set("Cache-Control", headers.cacheControl);
      stamped.headers.set("Cache-Tag", headers.cacheTag);
      return stamped;
    } catch {
      // Best-effort (CAVEATS): a cache-stamping failure must never break serving.
      return response;
    }
  },
} satisfies ExportedHandler<CloudflareEnv>;

// The OpenNext build currently emits these Durable Object exports even with the
// "dummy" cache config; wrangler resolves them from the generated bundle.
// @ts-ignore — same generated-module caveat as the import above.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
