#!/usr/bin/env node
/**
 * prod-connect — point a LOCAL `next dev` (PM on :3601, CMS on :3602) at the
 * PRODUCTION Cloudflare resources (D1, KV, R2, Images) via wrangler remote
 * bindings, and switch back.
 *
 *   node scripts/prod-connect.mjs cms <site-slug>   # local CMS -> that Site's prod D1/R2 + real PM
 *   node scripts/prod-connect.mjs pm                # local PM  -> prod D1 + KV
 *   node scripts/prod-connect.mjs local [cms|pm]    # restore local Miniflare (default: both)
 *   node scripts/prod-connect.mjs status
 *
 * How it works: the committed wrangler.jsonc is NEVER touched. We generate a
 * gitignored `wrangler.prod-remote.jsonc` (same config, bindings moved under
 * `env.prod-remote` with `remote: true` + real ids) and drop a
 * `.prod-remote.json` marker. next.config.ts sees the marker and boots
 * initOpenNextCloudflareForDev with that config + environment. Secrets for the
 * env live in the gitignored `.dev.vars.prod-remote` (fill once).
 *
 * Restart `npm run dev` after any switch — the config is read at boot.
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PM_DIR = join(ROOT, "ProjectManager");
const CMS_DIR = join(ROOT, "CMS");
const ENV_NAME = "prod-remote";
const GEN = "wrangler.prod-remote.jsonc";
const MARKER = ".prod-remote.json";
const SECRETS = `.dev.vars.${ENV_NAME}`;
const PM_ORIGIN = "https://manager.bizbeecms.com";
const PM_DB_NAME = "bizbeecms";
// Must match deployer/src/index.ts naming (DB_NAME / BUCKET_NAME).
const cmsDbName = (slug) => `bizbeecms-cms-${slug}`;
const cmsBucketName = (slug) => `bizbeecms-cms-media-${slug}`;

const [, , cmd, arg] = process.argv;

// ---------------------------------------------------------------- helpers ---
function die(msg) { console.error(`✗ ${msg}`); process.exit(1); }
function ok(msg) { console.log(`✓ ${msg}`); }

/** Strip // and /* *​/ comments from JSONC (string-aware) and parse. */
function parseJsonc(text) {
  let out = "", i = 0, inStr = false;
  while (i < text.length) {
    const c = text[i], n = text[i + 1];
    if (inStr) { out += c; if (c === "\\") { out += n; i += 2; continue; } if (c === '"') inStr = false; i++; continue; }
    if (c === '"') { inStr = true; out += c; i++; continue; }
    if (c === "/" && n === "/") { while (i < text.length && text[i] !== "\n") i++; continue; }
    if (c === "/" && n === "*") { i += 2; while (i < text.length && !(text[i] === "*" && text[i + 1] === "/")) i++; i += 2; continue; }
    out += c; i++;
  }
  // tolerate trailing commas
  return JSON.parse(out.replace(/,(\s*[}\]])/g, "$1"));
}

function wrangler(cwd, args, { json = false } = {}) {
  const out = execFileSync("npx", ["wrangler", ...args], { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  return json ? JSON.parse(out) : out;
}

/** Bindings are NOT inherited into wrangler environments — move them under env. */
const BINDING_KEYS = ["vars", "d1_databases", "kv_namespaces", "r2_buckets", "images", "send_email", "unsafe", "services", "queues", "ai", "browser", "vectorize", "hyperdrive"];

function buildConfig(base, { vars, d1, kv, r2 }) {
  const top = { ...base };
  const env = {};
  for (const k of BINDING_KEYS) if (k in top) { env[k] = top[k]; delete top[k]; }
  delete top.routes; // never bind local dev to prod routes
  env.vars = { ...(env.vars ?? {}), ...vars };
  if (env.d1_databases) env.d1_databases = env.d1_databases.map((d) => ({ ...d, ...(d1?.[d.binding] ?? {}), remote: true }));
  if (env.kv_namespaces) env.kv_namespaces = env.kv_namespaces.map((k) => ({ ...k, ...(kv?.[k.binding] ?? {}), remote: true }));
  if (env.r2_buckets) env.r2_buckets = env.r2_buckets.map((b) => ({ ...b, ...(r2?.[b.binding] ?? {}), remote: true }));
  if (env.images) env.images = { ...env.images, remote: true };
  // send_email stays LOCAL (logged, not sent) — remote would email real people.
  return { ...top, env: { [ENV_NAME]: env } };
}

function writeGenerated(dir, cfg, marker) {
  const banner = `// GENERATED by scripts/prod-connect.mjs — gitignored, do not edit.\n// Points local \`next dev\` at PRODUCTION resources (remote bindings). Run\n// \`scripts/prod-connect.mjs local\` to remove.\n`;
  writeFileSync(join(dir, GEN), banner + JSON.stringify(cfg, null, 2) + "\n");
  writeFileSync(join(dir, MARKER), JSON.stringify({ ...marker, env: ENV_NAME, config: GEN, at: new Date().toISOString() }, null, 2) + "\n");
}

function ensureSecrets(dir, template) {
  const p = join(dir, SECRETS);
  if (existsSync(p)) return false;
  writeFileSync(p, template);
  return true;
}

function disconnect(dir, label) {
  let did = false;
  for (const f of [GEN, MARKER]) { const p = join(dir, f); if (existsSync(p)) { unlinkSync(p); did = true; } }
  console.log(did ? `✓ ${label}: restored LOCAL (removed ${GEN}, ${MARKER})` : `· ${label}: already local`);
}

function status(dir, label) {
  const p = join(dir, MARKER);
  if (!existsSync(p)) { console.log(`· ${label}: LOCAL`); return; }
  const m = JSON.parse(readFileSync(p, "utf8"));
  console.log(`● ${label}: PROD-REMOTE ${m.slug ? `site=${m.slug} (${m.siteId})` : ""} since ${m.at}`);
}

// --------------------------------------------------------------- commands ---
function connectCms(slug) {
  if (!slug) die("usage: prod-connect cms <site-slug>");
  if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug)) die(`bad slug "${slug}"`);

  // Site id from the PROD PM D1 (read-only query).
  const rows = wrangler(PM_DIR, ["d1", "execute", PM_DB_NAME, "--remote", "--json", "--command",
    `select id, name, status, worker_name from sites where slug='${slug}'`], { json: true });
  const site = rows?.[0]?.results?.[0];
  if (!site) die(`no Site with slug "${slug}" in prod PM DB. Known: ${listSlugs().join(", ")}`);
  ok(`site ${slug} → id ${site.id} (${site.name}, ${site.status})`);

  const dbName = cmsDbName(slug);
  let dbId;
  try { dbId = wrangler(CMS_DIR, ["d1", "info", dbName, "--json"], { json: true }).uuid; } catch { /* fallthrough */ }
  if (!dbId) die(`D1 "${dbName}" not found — has this Site been deployed at least once?`);
  ok(`D1 ${dbName} → ${dbId}`);

  const bucket = cmsBucketName(slug);
  const buckets = wrangler(CMS_DIR, ["r2", "bucket", "list"]);
  if (!buckets.includes(bucket)) console.warn(`! R2 bucket ${bucket} not found — media will 404`);
  else ok(`R2 ${bucket}`);

  const base = parseJsonc(readFileSync(join(CMS_DIR, "wrangler.jsonc"), "utf8"));
  const cfg = buildConfig(base, {
    vars: { SITE_ID: site.id, PM_ORIGIN, APP_ORIGIN: "http://localhost:3602" },
    d1: { DB: { database_name: dbName, database_id: dbId } },
    r2: { MEDIA: { bucket_name: bucket } },
  });
  writeGenerated(CMS_DIR, cfg, { slug, siteId: site.id, dbId, bucket });
  const created = ensureSecrets(CMS_DIR, `# Secrets for prod-remote mode (gitignored). Loaded INSTEAD of .dev.vars when
# scripts/prod-connect.mjs cms <slug> is active. Do NOT put SITE_ID/PM_ORIGIN/
# APP_ORIGIN here — the generated wrangler.prod-remote.jsonc sets those.
#
# PM<->CMS shared bearer — the PRODUCTION value (same as the deployer's
# CMS_AUTH_SECRET). Empty => PM service calls (cms-validate/ai-config) 401;
# CMS_DEV_SUPERADMIN=1 in .env.local still lets you into the admin UI.
CMS_AUTH_SECRET=
# OpenRouter key for AI features while connected (your own dev key is fine).
OPENROUTER_API_KEY=
`);
  console.log(`\n✓ CMS → PROD site "${slug}". Wrote CMS/${GEN} + CMS/${MARKER}.`);
  if (created) console.log(`! Created CMS/${SECRETS} — fill CMS_AUTH_SECRET / OPENROUTER_API_KEY if you need PM calls / AI.`);
  console.log(`→ Restart the CMS dev server:  cd CMS && npm run dev\n  ⚠ Every write now hits the REAL Site database/bucket.`);
}

function listSlugs() {
  try {
    const rows = wrangler(PM_DIR, ["d1", "execute", PM_DB_NAME, "--remote", "--json", "--command", "select slug from sites order by slug"], { json: true });
    return rows?.[0]?.results?.map((r) => r.slug) ?? [];
  } catch { return []; }
}

function connectPm() {
  const base = parseJsonc(readFileSync(join(PM_DIR, "wrangler.jsonc"), "utf8"));
  const cfg = buildConfig(base, { vars: { APP_ORIGIN: "http://localhost:3601" } });
  writeGenerated(PM_DIR, cfg, {});
  const created = ensureSecrets(PM_DIR, `# Secrets for prod-remote mode (gitignored). Loaded INSTEAD of .dev.vars when
# scripts/prod-connect.mjs pm is active. Use the PRODUCTION values (from your
# password manager — wrangler cannot read deployed secrets back).
CMS_AUTH_SECRET=
SITE_SECRET_KEY=
OPENROUTER_PROVISIONING_KEY=
`);
  console.log(`\n✓ PM → PROD (D1 ${PM_DB_NAME} + KV SESSIONS/HOST_MAP). Wrote ProjectManager/${GEN} + ${MARKER}.`);
  if (created) console.log(`! Created ProjectManager/${SECRETS} — fill the production secrets.`);
  console.log(`→ Restart the PM dev server:  cd ProjectManager && npm run dev\n  ⚠ Every write now hits the REAL PM database + sessions.`);
}

switch (cmd) {
  case "cms": connectCms(arg); break;
  case "pm": connectPm(); break;
  case "local":
    if (!arg || arg === "cms") disconnect(CMS_DIR, "CMS");
    if (!arg || arg === "pm") disconnect(PM_DIR, "PM");
    console.log("→ Restart the affected dev server(s).");
    break;
  case "status": status(CMS_DIR, "CMS"); status(PM_DIR, "PM"); break;
  case "sites": console.log(listSlugs().join("\n")); break;
  default:
    console.log(`usage:
  prod-connect cms <site-slug>   local CMS -> that Site's PROD D1/R2 (+ real PM)
  prod-connect pm                local PM  -> PROD D1 + KV
  prod-connect local [cms|pm]    back to local Miniflare (default both)
  prod-connect status
  prod-connect sites             list Site slugs in prod PM`);
    process.exit(cmd ? 1 : 0);
}
